import type { Project, User, ProjectConfiguration, TeamMember } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Alice', avatar: 'https://placehold.co/100x100.png', email: 'alice@example.com', phone: '111-222-3333', role: 'Admin', status: 'active' },
  { id: 'user-2', name: 'Bob', avatar: 'https://placehold.co/100x100.png', email: 'bob@example.com', phone: '222-333-4444', role: 'Editor', status: 'active' },
  { id: 'user-3', name: 'Charlie', avatar: 'https://placehold.co/100x100.png', email: 'charlie@example.com', phone: '333-444-5555', role: 'Editor', status: 'active' },
  { id: 'user-4', name: 'Diana', avatar: 'https://placehold.co/100x100.png', email: 'diana@example.com', phone: '444-555-6666', role: 'Viewer', status: 'inactive' },
];

export const defaultConfiguration: ProjectConfiguration = {
    statuses: [
        { id: 'status-1', name: 'A Fazer', color: '#808080', isDefault: true },
        { id: 'status-2', name: 'Em Andamento', color: '#3b82f6' },
        { id: 'status-3', name: 'Concluído', color: '#22c55e', isCompleted: true },
        { id: 'status-4', name: 'Bloqueado', color: '#ef4444' },
    ],
    visibleKpis: {
        totalTasks: true,
        completedTasks: true,
        overallProgress: true,
        plannedBudget: true,
        actualCost: true,
        costVariance: true,
        spi: true,
        cpi: true,
    },
    customKpis: [],
    customCharts: [],
    customFieldDefinitions: [
      { id: 'sprint', name: 'Sprint', type: 'text' },
    ],
    alertRules: [
        { 
            id: 'alert-1', 
            metric: 'task_status', 
            condition: 'changes_to', 
            value: 'Bloqueado', 
            label: 'Alertar quando Status da Tarefa muda para Bloqueado' 
        },
        { 
            id: 'alert-2', 
            metric: 'budget_usage', 
            condition: 'exceeds_percentage', 
            value: '90', 
            label: 'Alertar quando Uso do Orçamento excede 90%'
        }
    ],
}

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'Sistema de E-commerce "Nexus"',
    description: 'Desenvolvimento de uma nova plataforma de e-commerce com foco em experiência do usuário e performance.',
    manager: users[0],
    team: [
      { user: users[0], role: 'Manager' },
      { user: users[1], role: 'Editor' },
      { user: users[2], role: 'Editor' },
      { user: users[3], role: 'Viewer' },
    ],
    plannedStartDate: '2024-01-01',
    plannedEndDate: '2024-06-30',
    actualStartDate: '2024-01-05',
    actualEndDate: '2024-07-15',
    plannedBudget: 500000,
    actualCost: 550000,
    configuration: defaultConfiguration,
    kpis: {
      'Variação de Prazo (dias)': 15,
      'Variação de Custo (R$)': -50000,
      'Progresso Total (%)': 85,
      'Tarefas Críticas Atrasadas': 2,
    },
    tasks: [
      {
        id: 'task-1',
        name: 'Fase 1: Planejamento e Design',
        assignee: users[0],
        status: 'Concluído',
        priority: 'Alta',
        plannedStartDate: '2024-01-01',
        plannedEndDate: '2024-01-31',
        actualStartDate: '2024-01-05',
        actualEndDate: '2024-02-05',
        plannedHours: 120,
        actualHours: 130,
        dependencies: [],
        isCritical: true,
        isMilestone: true,
        changeHistory: [
          {
            fieldChanged: 'plannedEndDate',
            oldValue: '2024-01-31',
            newValue: '2024-02-05',
            user: 'Alice',
            timestamp: '2024-01-20T10:00:00Z',
            justification: 'Atraso na definição de requisitos pelo cliente.',
          },
        ],
        subTasks: [
          {
            id: 'task-1-1',
            name: 'Levantamento de Requisitos',
            assignee: users[1],
            status: 'Concluído',
            priority: 'Alta',
            plannedStartDate: '2024-01-01',
            plannedEndDate: '2024-01-15',
            actualStartDate: '2024-01-05',
            actualEndDate: '2024-01-20',
            plannedHours: 40,
            actualHours: 45,
            dependencies: [],
            isCritical: true,
            changeHistory: [],
            customFields: { sprint: 'Sprint 1' }
          },
          {
            id: 'task-1-2',
            name: 'Design de UI/UX',
            assignee: users[2],
            status: 'Concluído',
            priority: 'Média',
            plannedStartDate: '2024-01-16',
            plannedEndDate: '2024-01-31',
            actualStartDate: '2024-01-21',
            actualEndDate: '2024-02-05',
            plannedHours: 80,
            actualHours: 85,
            dependencies: ['task-1-1'],
            isCritical: true,
            changeHistory: [],
            customFields: { sprint: 'Sprint 1' }
          },
        ],
      },
      {
        id: 'task-2',
        name: 'Fase 2: Desenvolvimento do Frontend',
        assignee: users[1],
        status: 'Em Andamento',
        priority: 'Alta',
        plannedStartDate: '2024-02-01',
        plannedEndDate: '2024-04-30',
        actualStartDate: '2024-02-06',
        actualEndDate: undefined,
        plannedHours: 300,
        actualHours: 250,
        dependencies: ['task-1'],
        isCritical: true,
        isMilestone: true,
        changeHistory: [],
        customFields: { sprint: 'Sprint 2' }
      },
      {
        id: 'task-3',
        name: 'Fase 3: Desenvolvimento do Backend',
        assignee: users[3],
        status: 'A Fazer',
        priority: 'Alta',
        plannedStartDate: '2024-02-15',
        plannedEndDate: '2024-05-15',
        actualStartDate: undefined,
        actualEndDate: undefined,
        plannedHours: 350,
        actualHours: 0,
        dependencies: ['task-1'],
        isCritical: true,
        isMilestone: true,
        changeHistory: [],
        customFields: { sprint: 'Sprint 3' }
      },
       {
        id: 'task-4',
        name: 'Fase 4: Testes e QA',
        assignee: users[2],
        status: 'Bloqueado',
        priority: 'Média',
        plannedStartDate: '2024-05-16',
        plannedEndDate: '2024-06-15',
        actualStartDate: undefined,
        actualEndDate: undefined,
        plannedHours: 150,
        actualHours: 0,
        dependencies: ['task-2', 'task-3'],
        isCritical: false,
        isMilestone: true,
        changeHistory: [],
        customFields: { sprint: 'Sprint 4' }
      },
       {
        id: 'task-5',
        name: 'Configurar CI/CD',
        assignee: users[3],
        status: 'A Fazer',
        priority: 'Baixa',
        plannedStartDate: '2024-06-16',
        plannedEndDate: '2024-06-30',
        actualStartDate: undefined,
        actualEndDate: undefined,
        plannedHours: 30,
        actualHours: 0,
        dependencies: ['task-4'],
        isCritical: false,
        changeHistory: [],
        customFields: { sprint: 'Sprint 4' }
      },
       {
        id: 'task-6',
        name: 'Deploy em Produção',
        assignee: users[0],
        status: 'A Fazer',
        priority: 'Alta',
        plannedStartDate: '2024-07-01',
        plannedEndDate: '2024-07-05',
        actualStartDate: undefined,
        actualEndDate: undefined,
        plannedHours: 20,
        actualHours: 0,
        dependencies: ['task-5'],
        isCritical: true,
        isMilestone: true,
        changeHistory: [],
        customFields: { sprint: 'Sprint 5' }
      },
    ],
  },
];
